import { ChildProps } from '@/types'
import type { Metadata } from 'next'
import { Nunito, Raleway } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'

const raleway = Raleway({
	variable: '--font-raleway',
	subsets: ['latin'],
})

const nunito = Nunito({
	variable: '--font-nunito',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Kinza',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildProps) {
	return (
		<html lang='en'>
			<body className={`${raleway.variable} ${nunito.variable} antialiased`}>
				{children}
				<Toaster position='top-center' />
			</body>
		</html>
	)
}
